Inferno timer improvements
runelite/runelite pull request #12430
Opened 2020-09-01 14:56 UTC by usa-usa-usa-usa

Closes #12401

Fixed inferno timer being 10 ticks (6 seconds) behind. Timer now starts at `00:06` once `Wave 1` message is displayed.

Elapsed timer now displays in `mm:ss` to be better inline with the ingame timer.

2020-09-01 15:10 UTC, Adam- commented on runelite-client/src/main/java/net/runelite/client/plugins/timers/ElapsedTimer.java
> +		final String formatString = "mm:ss";
I think that this rolls over from 59:59 to 00:00, which is wrong.

2020-09-04 07:01 UTC, Nightfirecat requested changes

2020-09-04 07:01 UTC, Nightfirecat commented on runelite-client/src/test/java/net/runelite/client/plugins/timers/ElapsedTimerTest.java
> +		assertEquals("55:00", timerText(oneHourAgo, fiveMinutesAgo));
This is a duplicate of the line above it--remove it

2020-09-04 07:01 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
> +					config.tzhaarStartTime(now.minus(Duration.ofSeconds(6)));
This would affect timers for both fight caves and inferno? If so, this isn't correct.

2020-09-10 00:39 UTC, Nightfirecat approved these changes

2020-09-15 02:01 UTC, Nightfirecat approved these changes

2020-09-21 04:53 UTC, merged