getHiscoreEndpointByNamehiscore: use correct endpoint when looking up self with shortcut
runelite/runelite pull request #12723
Opened 2020-10-30 15:53 UTC by Hydrox6

Currently, when using the shortcut to lookup yourself on the hiscores (double clicking the magnifying glass), the normal account tab is used no matter what was set before.

This makes it check the users account type, and makes it look up the correct account for that type. Also supports looking up league stats if you're on a league world!

2020-11-26 16:42 UTC, Adam- commented
I think this has already been fixed for looking up yourself, since `resetEndpoints()` calls `selectWorldEndpoint()` which identifies the world type. We could still do the per-account type lookup though but this is conflicting atm.

2021-01-15 23:13 UTC, Nightfirecat requested changes

2021-01-15 23:13 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
> +						NameAutocompleter nameAutocompleter, OkHttpClient okHttpClient)
```suggestion
		NameAutocompleter nameAutocompleter, OkHttpClient okHttpClient)
```

2021-01-15 23:13 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java
> +		}
This part of the logic could be replaced by `HiscorePanel#selectWorldEndpoint()`, e.g.:

```java
private HiscoreEndpoint getLocalHiscoreEndpoint()
{
	final HiscoreEndpoint profile = HiscorePanel.selectWorldEndpoint();
	if (profile != HiscoreEndpoint.NORMAL)
	{
		return profile;
	}

	switch (client.getAccountType())
	// ...
}
```

2021-01-17 14:42 UTC, Hydrox6 commented
I've moved some stuff around. 
* `selectWorldEndpoint` is now in the Plugin, renamed to `getWorldEndpoint`
* `getLocalHiscoreEndpointType` now has a null check, and uses `getWorldEndpoint`

2021-01-19 23:35 UTC, Nightfirecat approved these changes

2021-02-07 22:59 UTC, Hydrox6 commented
Earlier, a conversation was had on Discord about getting this to also work off of chat message, since the information is available. The PR now covers this.

2021-02-09 07:00 UTC, Nightfirecat requested changes

2021-04-13 22:32 UTC, Adam- commented on runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java
> +				if (endpoint == HiscoreEndpoint.NORMAL)
Players can dm you from other worlds, so it probably would be best to just not check this. Or maybe check the flags of the world they are in, but those aren't always available.

2021-04-13 22:32 UTC, Adam- commented on runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java
>  	private void lookupPlayer(String playerName)
This is only use one other place, might aswell remove it and use the one which takes the endpoint.

2021-04-13 22:32 UTC, Adam- commented on runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java
> +		return null;
I see no reason why this should ever be able to default to anything other than `NORMAL`

2021-04-13 22:32 UTC, Adam- commented on runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java
> +		Matcher macther = COL_STRIPPER.matcher(rawName);
Instead of this, you could just contains() the name with IconID.toString()

2021-04-13 23:57 UTC, merged