Add redwood objects and log message
runelite/runelite pull request #13099
Opened 2021-01-23 10:47 UTC by pwatts6060

2021-02-09 06:25 UTC, Nightfirecat requested changes
@leejt to review

2021-02-09 06:25 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/woodcutting/CrowdsourcingWoodcutting.java
> +			add(34633, 34635, 34637, 34639). //redwood tree patch farming guild
Use the variables found in NullObjectID

2021-02-09 06:25 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/woodcutting/CrowdsourcingWoodcutting.java
> +			add(ObjectID.OAK).
Indentation needs to be fixed in this file. All these changed lines should have two leading tabs, not three.

2021-02-15 02:44 UTC, Nightfirecat reviewed
LGTM

2021-02-15 02:44 UTC, Nightfirecat commented
@leejt Please review this PR

2021-02-15 03:53 UTC, leejt commented
For the farming trees, the MenuOptionClicked's ID will always be that of the base patch, rather than the tree it's been transformed into. I'd suggest removing the farming-related IDs instead of trying to wrangle the ID out of it (especially because farming trees are particularly weird to begin with, and they probably aren't the primary source of redwood data anyway).

Cooking changes LGTM - it might be nice to figure out the spider and snail messages too.

2021-02-15 05:35 UTC, pwatts6060 commented
> For the farming trees, the MenuOptionClicked's ID will always be that of the base patch, rather than the tree it's been transformed into. I'd suggest removing the farming-related IDs instead of trying to wrangle the ID out of it (especially because farming tree tick mechanics are particularly weird to begin with, and they probably aren't the primary source of redwood data anyway).
> 
> Cooking changes LGTM - it might be nice to figure out the spider and snail messages too.

Ok I removed the redwood farming tree objects.

I checked the farming messages for snails and spiders and the current stuff already covers it I think. 
`|| message.startsWith("You accidentally burn")`
"You accidentally burn the spider."
"You accidentally burn the snail."

`|| message.startsWith("You cook")`
"You cook a spider."
"You cook the fat snail."
"You cook the lean snail."
"You cook the thin snail."

2021-02-15 06:41 UTC, merged