Add swap bait with lure menu entry swap config for fishing spot
runelite/runelite pull request #13203
Opened 2021-02-11 22:01 UTC by pwatts6060

2021-02-11 22:35 UTC, dekvall requested changes

2021-02-11 22:35 UTC, dekvall commented on runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
> +			section = objectSection
Dedent these lines.

2021-02-15 08:05 UTC, Nightfirecat requested changes
This also needs to be rebased on master.

2021-02-15 08:05 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
> +		swap("lure", "bait", config::swapBait);
Cave eels also have "Bait" options, as do some mystery Net / Bait spots. They should be covered the same way as the harpoon spots.

2021-02-15 23:39 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
> +		description = "Swap Small Net, Net, Lure with with Bait on Fishing spot",
I'll commot this with GitHub's UI
```suggestion
		description = "Swap Small Net, Net, Lure with Bait on Fishing spot",
```

2021-02-15 23:41 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
> +		description = "Swap Small Net, Net, Lure with Bait on Fishing spot",
```suggestion
		description = "Swap Lure, Small Net with Bait on Fishing spot",
```

2021-02-15 23:49 UTC, merged