Add minimap arrow pointing to the active daeyalt rock
runelite/runelite pull request #13217
Opened 2021-02-14 03:36 UTC by NJohnsonJ

![Example](https://user-images.githubusercontent.com/37092015/107867788-5b62d500-6e43-11eb-82b5-b426ccfadb0d.png)

2021-02-16 07:44 UTC, Nightfirecat requested changes

2021-02-16 07:44 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
> +				client.clearHintArrow();
This should check that the hint arrow being cleared is at the same point as the despawned essence via `Client#getHintArrowType()` and `Client#getHintArrowPoint()`. It's possible that the hint arrow was set by the client or by another plugin, so we should not presume that this plugin is the only thing setting it.

2021-02-18 03:38 UTC, Nightfirecat requested changes
The only other issue I noticed is that shutting down the plugin does not clear the hint arrow if it is set. You should be able to call `clearDaeyaltHintArrow()` on the contents of `respawns` before it is cleared to resolve that.

2021-02-18 03:38 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
> +			client.clearHintArrow();
This project avoids the use of one-line `if` statements. Add braces to the `clearHintArrow()` call.
```suggestion
		if (client.getHintArrowType() == WORLD_POSITION && client.getHintArrowPoint().equals(object.getWorldLocation()))
		{
			client.clearHintArrow();
		}
```

2021-02-18 05:12 UTC, Nightfirecat commented
I've pushed a commit which cleans up this PR to apply with fewer deletions than 6ea82e7 and clean up the flow a bit.

2021-02-19 01:10 UTC, NJohnsonJ commented
Is anything else required of me to get this merged?

2021-02-19 03:34 UTC, merged