Add new utility methods for checking if world points are inside world areas
runelite/runelite pull request #13211
Opened 2021-02-13 10:50 UTC by pwatts6060

These utility methods are useful in plugins both for the hub and runelite. I swapped out one of the old ways it was done in the NpcAggroAreaPlugin as an example. I ran some unit tests and the methods seem to functionally be the same as the distance == 0 checks.

2021-02-15 07:47 UTC, Nightfirecat reviewed
Isn't this the same as `WorldPoint.distanceTo(WorldArea other) == 0`?

2021-02-15 10:36 UTC, pwatts6060 commented
> Isn't this the same as `WorldPoint.distanceTo(WorldArea other) == 0`?

Yes it serves the same purpose but less verbose and can do checks for multiple areas rather than chaining them with ors.

2021-02-15 23:59 UTC, Nightfirecat commented
> ... and can do checks for multiple areas rather than chaining them with ors.

I don't understand this at all. Can you give an example where this proposed API is better than what I posted?

2021-02-16 13:38 UTC, pwatts6060 commented
> > ... and can do checks for multiple areas rather than chaining them with ors.
> 
> I don't understand this at all. Can you give an example where this proposed API is better than what I posted?
People search the api to find a method for if a point is contained within an area. With the current api you won't find anything you want for that, most people won't immediately realize they can do the distance == 0 check. You shouldn't need to get the distance and compare it with 0 though. 

It's a lot more readable and often you need to check if a point is in any areas such as the one I swapped out in the NpcAggroAreaPlugin. I'm sure it will also get lots of use for plugins on the hub. e.g.
`inLobby = client.getLocalPlayer().getWorldLocation().distanceTo(lmsCompetitiveLobby) == 0
			|| client.getLocalPlayer().getWorldLocation().distanceTo(lmsCasualLobby) == 0
			|| client.getLocalPlayer().getWorldLocation().distanceTo(lmsHighStakesLobby) == 0;`
vs 
`inLobby = client.getLocalPlayer().getWorldLocation().inArea(lmsCompetitiveLobby, lmsCasualLobby, lmsHighStakesLobby);`

2021-02-18 07:16 UTC, Nightfirecat requested changes
Also please write full javadoc, eg. description, `@param`(s), and `@return`

2021-02-18 07:16 UTC, Nightfirecat commented on runelite-api/src/main/java/net/runelite/api/coords/WorldArea.java
> +			&& contains2D(worldPoint);
```suggestion
		return distanceTo(worldPoint) == 0;
```

2021-02-18 07:16 UTC, Nightfirecat commented on runelite-api/src/main/java/net/runelite/api/coords/WorldArea.java
> +			&& worldPoint.getY() >= y && worldPoint.getY() <= y + height;
```suggestion
		return distanceTo2D(worldPoint) == 0;
```

2021-09-14 09:30 UTC, pwatts6060 commented
@Nightfirecat Added javadocs and commited your changes

2021-09-21 08:07 UTC, merged