Plugin: Menu entry swap for Travel/Dive on rowboat in Fossil Island
runelite/runelite pull request #13237
Opened 2021-02-19 16:41 UTC by joelewis43

Close #13232

Adds a Menu Entry Swap option for the Fossil Island Rowboat. Swaps the Travel option with Dive.

2021-02-19 23:45 UTC, Nightfirecat requested changes

2021-02-19 23:45 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
> +			name = "Fossil Island Rowboat",
This should specify the action being swapped, e.g. `Fossil Island Rowboat Dive`

2021-02-19 23:45 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
> +			description = "Swap Travel with Dive for the rowboat just off of Fossil Island",
```suggestion
			description = "Swap Travel with Dive on the rowboat found on the small island north-east of Fossil Island",

```

2021-02-20 18:36 UTC, joelewis43 reviewed
Done

2021-02-20 22:54 UTC, merged