chat notifications: Prevent localPlayer highlights and notifications
runelite/runelite pull request #13244
Opened 2021-02-20 18:14 UTC by Broooklyn

Fixes #13238

2021-02-20 21:23 UTC, Nightfirecat requested changes
The tests for this plugin currently pass regardless of whether this is applied, so some test changes are needed to provide coverage. You should be able to mock a localPlayer response in whatever added tests you provide without impacting the coverage of the existing tests.

2021-02-22 18:50 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
> +					messageNode.setValue(messageNode.getValue());
Behavior-wise, this is a no-op?

2021-02-23 08:20 UTC, Nightfirecat requested changes

2021-02-23 08:20 UTC, Nightfirecat commented on runelite-client/src/test/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPluginTest.java
> +		lenient().when(config.notifyOnHighlight()).thenReturn(true);
Neither test is specifically testing notifications; only the name/words highlight configs need to be mocked in the added tests.

2021-02-23 08:20 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
> +				if (client.getLocalPlayer() != null && chatMessage.getName().equals(client.getLocalPlayer().getName()))
This fails for players with spaces in their name. `Player#getName()` appears to return a normal space, while `ChatMessage#getName()` uses a nbsp. It's likely safest to assume both strings must be run through `Text#toJagexName()`.

The test case covering this should be updated as well.

2021-02-23 16:15 UTC, Broooklyn commented
Updated per your review.  It was also necessary to wrap `chatMessage.getName()` in `Text.removeTags()` in addition to `Text.toJagexName()` to account for Ironmen players.

That said, I am fairly certain `Text#toJagexName()` does not have any effect on `client.getLocalPlayer().getName()` so I have ommited it from that side of the comparison.

2021-02-27 19:40 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
> +				if (client.getLocalPlayer() != null && Text.toJagexName(Text.removeTags(chatMessage.getName())).equals((client.getLocalPlayer().getName())))
One too many parens around the localplayer name call
```suggestion
				if (client.getLocalPlayer() != null && Text.toJagexName(Text.removeTags(chatMessage.getName())).equals(client.getLocalPlayer().getName()))
```

2021-02-28 19:22 UTC, merged