Add item stats in equipment tab
runelite/runelite pull request #13247
Opened 2021-02-20 19:54 UTC by NJohnsonJ

Resolves #12628 
* Add unit tests for new methods and to test the 2H logic
* Fix and simplify the 2H logic
* Add config option to turn off equipment stats in the equipment tab
* Add javadoc for buildItemTooltip

2021-02-20 23:40 UTC, Nightfirecat requested changes
This PR should be comprised of a couple commits:

1. Simplify and fix 2h logic (and add tests for 2h logic; these tests should fail on master and pass after this commit is applied)
2. Add equipment tab stats config, add tooltip method javadoc (?)

As-is, this is hard to review because multiple features are all being added in one giant change without any distinction regarding which code changes are attributed to which logical changes.

2021-02-20 23:40 UTC, Nightfirecat commented on http-api/src/main/java/net/runelite/http/api/item/ItemStats.java
> +	public static final ItemStats UNARMED = new ItemStats(false, true, 0, 0,
This shouldn't be stored here since it's not used in this class. It should probably continue to remain in the overlay class.

2021-02-20 23:40 UTC, Nightfirecat commented on http-api/src/main/java/net/runelite/http/api/item/ItemStats.java
> +					: NOTHING.getEquipment();
These lines along with the ItemEquipmentStatsBuilder continuation lines below are indented one level too far.
```suggestion
				? this.equipment
				: NOTHING.getEquipment();
```

2021-02-21 04:19 UTC, NJohnsonJ commented
I'm going to close this PR, update the commits and reopen once it is fixed.

2021-02-21 04:19 UTC, closed without merging