Fix restored window size when client is fullscreen
runelite/runelite pull request #13835
Opened 2021-07-04 19:50 UTC by MarkKoester

Fixes #2612 and related to #3574

Currently, when the plugin panel or sidebar is shown while the client is fullscreen, and the client is restored, the updated size of the client is not respected.

This pull request makes two changes to fix this issue. First, `revalidateMinimumSize()` is moved in the `expandBy()` and `contractBy()` functions to be called before the return path when the client is maximized. This should guarantee that the minimum size is still captured in all situations.

Second, the client size is manually set when the window is restored. When the window is restored, it's set back to it's size before it was maximized regardless of the minimum size, so the size has to be manually set. Since the `setSize()` function respects the frames minimum size, I just call `setSize()` with the frames current size and it works as desired.

Alternatively, the onResize listener could check for whether the frame state was previously maximized and is now not maximized, but the current approach seems a bit simpler. I'm not sure which one would necessarily be better.

Also, I'm not exactly sure if adding the component listener should be done in ClientUI or the ContainableFrame class, so I'd be interested in getting feedback there.

2021-07-04 21:34 UTC, abextm requested changes

2021-07-04 21:34 UTC, abextm commented on runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
> +					super.componentResized(e);
you don't need a super call here

2021-07-04 21:34 UTC, abextm commented on runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
> +					frame.setSize(frame.getSize());
this should have a comment

2021-07-04 21:55 UTC, MarkKoester commented on runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
> +					frame.setSize(frame.getSize());
Done

2021-07-04 21:55 UTC, MarkKoester commented on runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
> +					super.componentResized(e);
Done

2021-07-05 23:36 UTC, abextm approved these changes

2021-07-10 12:03 UTC, WooxSolo commented
The minimum size is 8 pixels off in both width and height when unmaximizing the window after expanding or contracting the sidebar in maximized mode with custom chrome enabled from my testing on Windows 10. Would guess this is due to custom chrome adding 4 pixels to the border in unmaximized mode but not in maximized mode, so revalidating the minimum size in maximized mode gives a slightly wrong minimum size.

2021-10-02 17:30 UTC, Adam- commented
1) I've looked at these `revalidateMinimumSize` calls but I do not see any behavior change by changing them alone. When the client is maximized everything still behaves correctly since you cannot make the window smaller without unmaximizing it. So I don't think it is even necessary to change this to fix this problem?

At best maybe it ensures the minimum size is always valid even when maximized but I'm not sure if this is useful? Do you know why you are trying to change this?

2) I think that this is just needing to recompute the minimum size whenever the frame state is changed, similar to what #3574 is doing. 

3) I too see the minimum size being slightly too small with this like Woox said - even also with #3574. I figured out just putting the resize call in an invokeLater() fixes it. Not sure.

So I think that this commit fixes these issues instead: https://github.com/Adam-/runelite/commit/ab2658b6a6fa0a644ac754423cbf34d1188b1b02. Can you check and see if it works for you?

cc @jplsek

2021-10-04 17:45 UTC, Adam- commented
I tested this some more and think it's probably fine so I've pushed it. Reopen or comment on #2612 if its still a problem.

2021-10-04 17:45 UTC, closed without merging