item identification: Add supplies in Tombs of Amascut
runelite/runelite pull request #15581
Opened 2022-08-30 06:58 UTC by Molorius

Item Identification plugin: Add supplies in Tombs of Amascut. Please let me know if any names should be changed.

2022-08-30 13:15 UTC, Molorius commented
The item identification changes are mentioned in #15478. I forced a few commits to fix styling, change wording slightly, and to add Honey Locust.

2022-09-08 04:41 UTC, Nightfirecat requested changes
Why is there a new section added for new types of items? We don't do blanket item identification for all types of food/consumables, only potions. Please remove `SUPPLIES_TOA` and all non-potion items added here, and move the potion definitions to the appropriate section.

2022-09-16 00:31 UTC, Molorius commented
I kept only the potions and moved them to the potions section. I just retested Nectar and Ambrosia, I can test the others if needed.

2022-10-04 22:49 UTC, Nightfirecat commented on runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentification.java
> +	TEARS_OF_ELIDINIS(Type.POTION, "TearsOE", "ToE", ItemID.TEARS_OF_ELIDINIS_4, ItemID.TEARS_OF_ELIDINIS_3, ItemID.TEARS_OF_ELIDINIS_2, ItemID.TEARS_OF_ELIDINIS_1),
```suggestion
	TEARS_OF_ELIDINIS(Type.POTION, "Tears", "ToE", ItemID.TEARS_OF_ELIDINIS_4, ItemID.TEARS_OF_ELIDINIS_3, ItemID.TEARS_OF_ELIDINIS_2, ItemID.TEARS_OF_ELIDINIS_1),
```

2022-10-04 22:52 UTC, merged