Add Ghommal's Hilt Teleport Locations on World Map
runelite/runelite pull request #16022
Opened 2022-12-13 04:05 UTC by KPGoik

Resolves Issue [#16006](https://github.com/runelite/runelite/issues/16006).

2022-12-13 04:25 UTC, KPGoik commented
Didn't get ahead of myself this time waiting for the tests to go through...

Done! This resolves issue #16006

2022-12-18 12:57 UTC, raiyni requested changes
We don't differentiate between different diary reward levels for other items.

2022-12-18 12:57 UTC, raiyni commented on runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java
> +	GHOMMALS_HILT_GWD(TeleportType.OTHER, "Ghommal's hilt 1", "God Wars Dungeon", new WorldPoint(2898, 3709, 0), "ghommals_hilt_1_teleport_icon.png"),
```suggestion
	GHOMMALS_HILT_GWD(TeleportType.OTHER, "Ghommal's hilt", "God Wars Dungeon", new WorldPoint(2898, 3709, 0), "ghommals_hilt_teleport_icon.png"),
```

2022-12-18 12:57 UTC, raiyni commented on runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java
> +	GHOMMALS_HILT_MORULREK(TeleportType.OTHER, "Ghommal's hilt 4", "Mor Ul Rek", new WorldPoint(2554, 5130, 0), "ghommals_hilt_4_teleport_icon.png"),
```suggestion
	GHOMMALS_HILT_MORULREK(TeleportType.OTHER, "Ghommal's hilt", "Mor Ul Rek", new WorldPoint(2554, 5130, 0), "ghommals_hilt_teleport_icon.png"),
```

2022-12-31 21:53 UTC, ragnarokatz commented
do you mind if I take over and continue to work on this issue?

2023-01-05 16:10 UTC, raiyni commented
@ragnarokatz go for it

2023-01-12 15:43 UTC, raiyni commented
added in 9f3b6958fba80923c2926acd5ef3735b77b3e15b

2023-01-12 15:43 UTC, closed without merging