groundmarkers: Fix minimap stroke
runelite/runelite pull request #16801
Opened 2023-07-19 02:51 UTC by CoreyForsyth

2023-07-19 02:54 UTC, raiyni commented
What issue is this fixing?

2023-07-19 03:22 UTC, Adam- commented
It looks like this was double-drawing the polygon. Playing around with it locally I think it is better to just drop the `renderPolygon` call instead. `renderPolygon` additionally does an alpha fill, but the minimap is so small it isn't really noticeable so it would be best to not do it.

2023-07-19 03:47 UTC, CoreyForsyth commented
Updated to remove the `renderPolygon` call. Thank you

2023-07-19 18:55 UTC, Adam- requested changes
you are missing the setColor() call

2023-07-20 00:43 UTC, CoreyForsyth commented
![image](https://github.com/runelite/runelite/assets/22247745/f422d44c-fb8e-4be0-b730-2f6124fef6cc)
Before -> After at default zoom

2023-07-20 02:33 UTC, Adam- approved these changes

2023-07-20 02:33 UTC, merged