grandexchange: fuzzy with prefix + jarowinkler
runelite/runelite pull request #16973
Opened 2023-08-28 18:19 UTC by LlemonDuck

Replaces the GE plugin's fuzzy search with a new algorithm: a weighted score between the shared prefix length of the query and item names, and the Jaro-Winkler proximity score. The previous algorithm checked for the length of subsequence in the item name relative to the query.

## Prior behaviour:
![](https://cdn.discordapp.com/attachments/419891709883973642/1143589991516213339/image.png)
![image](https://github.com/runelite/runelite/assets/1868974/136098d3-3da9-420d-a92b-d53524819607)

## New behaviour:
![image](https://github.com/runelite/runelite/assets/1868974/44f54772-6ca9-4903-b871-5e117526389f)
![image](https://github.com/runelite/runelite/assets/1868974/6a2220ce-90e3-4481-9286-dd2cd9548b0e)

2023-09-18 14:38 UTC, raiyni requested changes

2023-09-18 14:38 UTC, raiyni commented on runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/FuzzySearchScorer.java
> +package net.runelite.client.plugins.grandexchange;
Needs license

2023-09-24 20:34 UTC, LlemonDuck commented on runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/FuzzySearchScorer.java
> +package net.runelite.client.plugins.grandexchange;
license added

2023-09-24 22:06 UTC, raiyni approved these changes

2024-07-12 18:27 UTC, raiyni commented
Needs rebased

2024-07-15 03:39 UTC, merged