clues: allow confining clues to regions
runelite/runelite pull request #17235
Opened 2023-11-27 11:25 UTC by Macweese

This PR brings the ability for implementors of `NpcClueScroll` to confine the NPC marking to region IDs. This prevents false positive associations, between NPCs and clues by the clue scroll plugin, when displaying hints and overlays.

Currently the clue scroll plugin will, for certain clues, mark NPCs indiscriminately of whether they are linked to the clue or not. This is mainly due to using string comparisons, where the plugin will solicit for any NPCs with the same name and treat all matches as the intended target. This results in e.g. all NPCs named "Bartender" being marked, when in fact _a specific_ Bartender is sought.

To solve this, I played around with different solutions such as using NPC IDs/NPC compositions instead of string matching, and while they work, I ultimately opted for this approach since it entails a lesser change, avoiding shotgun surgery, for the same result. Additionally, some clues require area based value checks anyway[^1]. In my opinion though, I think using NPC IDs instead of strings is superior for these purposes.

The current changes only encompass `CrypticClue` clues, I skimmed through the other types but didn't find any clues which may infer restrictions to NPCs by variance in the same way.

Changes
• Add optional regions to the `NpcClueScroll` interface
• Amend respective `CrypticClues`

Fixes #5231

[^1]: For example the clue "_In a town where wizards are known to gather, search upstairs in a large house to the north._" involves the generic NPC "Man", but is restricted to Yanille.

2023-11-27 13:30 UTC, Skretzo commented on runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
> +	private CrypticClue(String text, String npc, WorldPoint location, int[] regions, String solution)
A new class to instead specify a clue NPC through a combination of name, ID and/or region IDs could also be useful, but I understand that you wanted to keep this change small.

2023-11-27 14:03 UTC, Adam- commented
It might be better to use `WorldArea` to represent the npc regions instead of a list of region ids.

2023-11-27 14:25 UTC, Adam- commented
> It's a far more precise solution, no doubt, though I felt it was "messier" if that makes sense. The determining factor was that there are no instances of clues whose NPCs and regions coincide (as of now).

If the NPCs and regions don't coincide wouldn't WorldArea be better because the areas are not region constrained?

2023-11-27 15:13 UTC, Adam- commented
> The determining factor was that there are no instances of clues whose NPCs and regions coincide (as of now).

I interpreted the "NPCs and regions coincide" to mean where the NPCs cleanly fit into regions (or region boundaries).

This looks like instead you mean there are not two clues who have both the same npc *and* region? Having two clues with the same npc and region do not matter though because the clue matching is performed via text matching.

2023-11-27 16:16 UTC, Adam- commented
> > Having two clues with the same npc and region do not matter though because the clue matching is performed via text matching.
> 
> I don't understand this, I don't believe this is related. These changes affect clues with NPCs who share names, not two clues who share a name/NPC. As mentioned [here](https://github.com/runelite/runelite/pull/17235#issue-2012061918):

As far as I can tell whether or not two clues have the same region + npcs or not is completely irrelevant to anything being proposed here, and also to the existing implementation. It has no effect on either region vs world area. So I don't understand why you are using it as a "determining factor" in whether to use world area or region id.

2023-11-27 20:40 UTC, Adam- commented
> I intended to refer to _clues_ with the word coincide, not the clues' attributes of NPCs and regions. Meaning: there are no two clues, whose attributes of both NPCs and regions, are the same.
> 
> > This looks like instead you mean there are not two clues who have both the same npc and region?
> 
> Yes, that is what I meant to say.

I think the confusion here is actually you mean: there are no two clues with distinct npcs with the same name and region.

Having two clues with the same npc and region, regardless of your interpration of "npc" to mean either "npc name" or "npc id", is never a problem.

2023-11-27 21:33 UTC, Adam- requested changes
it may be worth using a builder at some point, the constructor overloads are starting to get a little much

2023-11-27 21:33 UTC, Adam- commented on runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
> +		new CrypticClue("Talk to the bartender of the Rusty Anchor in Port Sarim.", "Bartender", new WorldPoint(3045, 3256, 0), new int[]{11569}, "The Rusty Anchor is located in the north of Port Sarim."),
11569 is 2880,3136, which is Musa point and is wrong.

2023-11-27 21:33 UTC, Adam- commented on runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
> +		new CrypticClue("In a town where thieves steal from stalls, search for some drawers in the upstairs of a house near the bank.", "Guard", DRAWERS, new WorldPoint(2611, 3324, 1), new int[]{10547}, "K
there are guards outside of 41,51 that work for this too, such as by the north bank in 41,52. I would probably include the whole ardy area.

2023-11-27 21:33 UTC, Adam- commented on runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
> +		new CrypticClue("You'll need to look for a town with a central fountain. Look for a locked chest in the town's chapel.", "Monk" , CLOSED_CHEST_5108, new WorldPoint(3256, 3487, 0), new int[]{12086},
12086 is 47,54 which is the edgeville monastery

2023-12-30 00:00 UTC, Adam- commented
added in 3084c56929b0f0e19e66366c2a6242d2157ec6e6

2023-12-30 00:00 UTC, closed without merging