Removes GE/HA display for coins.
runelite/runelite pull request #3889
Opened 2018-06-18 20:27 UTC by cherrydipped

Requested on discord.

2018-06-18 20:38 UTC, deathbeam requested changes

2018-06-18 20:38 UTC, deathbeam commented on runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
> +				if (item.getItemId() == 995)
Why is this specific only for PriceDisplayMode.BOTH? Also, shouldn't this condition be inversed? Also, use ItemID.COINS_995

2018-06-19 01:17 UTC, HSJ-OSRS commented
would enclosing it all in a singular if statement not be better
```java
			if (item.getItemId() != ItemID.COINS_995)
			{
				if (config.priceDisplayMode() == PriceDisplayMode.BOTH)
				{
					if (item.getGePrice() > 0)
					{
						itemStringBuilder.append(" (EX: ")
							.append(StackFormatter.quantityToStackSize(item.getGePrice()))
							.append(" gp)");
					}

					if (item.getHaPrice() > 0)
					{
						itemStringBuilder.append(" (HA: ")
							.append(StackFormatter.quantityToStackSize(item.getHaPrice()))
							.append(" gp)");
					}
				}
				else if (config.priceDisplayMode() != PriceDisplayMode.OFF)
				{
					final int price = config.priceDisplayMode() == PriceDisplayMode.GE
						? item.getGePrice()
						: item.getHaPrice();

					if (price > 0)
					{
						itemStringBuilder
							.append(" (")
							.append(StackFormatter.quantityToStackSize(price))
							.append(" gp)");
					}
				}
			}
```

2018-06-22 10:18 UTC, deathbeam requested changes

2018-06-22 10:18 UTC, deathbeam commented on runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
> +import net.runelite.api.*;
Fix imports (https://github.com/runelite/runelite/wiki/Code-Conventions)

2018-06-25 08:43 UTC, deathbeam requested changes

2018-06-25 08:43 UTC, deathbeam commented on runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Remove this empty line

2018-06-25 09:30 UTC, deathbeam approved these changes

2018-06-25 09:31 UTC, deathbeam requested changes

2018-06-25 09:31 UTC, deathbeam commented on runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
> -
Why was this new line removed? Add it back

2018-06-25 09:31 UTC, deathbeam commented on runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
> -
Why was this newline removed? Add it back

2018-06-25 18:47 UTC, deathbeam approved these changes

2026-07-03 06:59 UTC, closed without merging